name: CI Test A Master

on:
  pull_request:

jobs:

  update-version:
    runs-on: ubuntu-latest
    name: Update Config.yml

    steps:
      # - name: Checkout CI Test A
      #   uses: actions/checkout@v3
      #   with:
      #     ref: 'master'
      - name: Checkout CI Test B
        uses: actions/checkout@v3
        with:
          repository: maxsuhak/ci-test-b
          ssh-key: ${{ secrets.GITBOT_SSH_KEY }}
          path: ./ci-test-b

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          workdir: ./ci-test-b
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: List keys
        run: gpg -K

      # - name: Change version
      #   run: |
      #     current_version=$(head -n 1 ./VERSION)
      #     current_date=$(date +'%Y-%m-%d')
      #     hex=$(echo $RANDOM | md5sum | head -c 16; echo;)
      #     app_version="${current_version}_${current_date}_${hex}"
      #     awk -v app_version="  app:version: ${app_version}" '{sub("^  app:version: (.*)$", app_version)}1' ./config.yml > tmp.yml && mv tmp.yml ./config.yml
      # - name: Push CI
      #   run: |
      #     git add ./config.yml
      #     git commit -S -m "Updating config.yml#app:version"
      #     git push

      - name: Change version
        run: |
          current_version=$(echo '999.999.999')
          current_date=$(date +'%Y-%m-%d')
          hex=$(echo $RANDOM | md5sum | head -c 16; echo;)
          app_version="${current_version}_${current_date}_${hex}"
          awk -v app_version="  app:version: ${app_version}" '{sub("^  app:version: (.*)$", app_version)}1' ./ci-test-b/VERSION.yml > ./ci-test-b/tmp.yml && mv ./ci-test-b/tmp.yml ./ci-test-b/VERSION.yml

      - name: Push CI
        run: |
          cd ./ci-test-b
          git add ./VERSION.yml
          git commit -S -m "Updating VERSION.yml#app:version"
          git push
