name: CI Test A Master

on:
  pull_request:

jobs:
  update-version:
    runs-on: ubuntu-latest
    name: Update Version
    needs: build

    steps:
      - name: Checkout CI Test A
        uses: actions/checkout@v3
        with:
          ref: 'master'

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: List keys
        run: gpg -K

      # -
      #   name: Import GPG key
      #   uses: crazy-max/ghaction-import-gpg@5
      #   with:
      #     gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.GPG_PASSPHRASE }}
      #     git_config_global: true

      # -
      #   name: List keys
      #   run: gpg -K

      # -
      #   name: Change version
      #   run: |
      #     current_version=$(head -n 1 ./ci-test-a/VERSION)
      #     current_date=$(date +'%Y/%m/%d')
      #     hex=$(echo $RANDOM | md5sum | head -c 20; echo;)
      #     app_version="${current_version}-${current_date}-${hex}"
      #     awk -v app_version="  app:version: ${app_version}" '{sub("^  app:version: (.*)$", app_version)}1' ./ci-test-b/VERSION.yml > tmp.yml && mv tmp.yml ./ci-test-b/VERSION.yml
      # -
      #   name: Push CI Test B
      #   run: |
      #     cd ./ci-test-b
      #     git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
      #     git config --global user.name ${{ secrets.GIT_USER_NAME }}
      #     git config --global user.signingkey ${{ secrets.GPG_SIGNINGKEY }}
      #     export GPG_TTY=$(tty)
      #     git add .
      #     git commit -S -m "Updating app:version"
      #     git push
